[package]
name = "krpc"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Martin Cong <cyy2cyy@gmail.com>"]

[dependencies]
prost = "0.13.1"
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
tonic = "0.12.1"

[build-dependencies]
tonic-build = "0.12.1"
