[package]
name = "krpc"
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"
license = "Apache-2.0"
authors = ["Martin Cong <cyy2cyy@gmail.com>"]
exclude = ["examples/"]


# [lib]
# name = "krpc"
# path = "src/lib.rs"

# [[bin]]
# name = "rpcurl"
# path = "src/bin/rpcurl.rs" 

[features]
svr = ["dep:const-str", "dep:tonic", "dep:tonic-prost", "tonic?/router", "tonic?/server"]
clt = [
    "dep:rustls",
    "dep:tonic",
    "dep:tonic-prost",
    "tonic?/tls-native-roots",
    #"tonic?/channel","tonic?/tls",
    # https://github.com/rust-lang/rustup/issues/3400#issuecomment-1683762630
]
default = ["svr"]

[dependencies]
prost = "0.14.3"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros"] }
tonic = { version = "0.14.6", default-features = false, features = ["codegen"] ,optional = true }
tonic-prost = { version = "0.14.6", optional = true }

# client side
rustls = { version = "0.23.40", optional = true }
# server side
const-str = { version = "1.1.0", optional = true }


[dev-dependencies]
krpc = { path = ".", features = ["clt","svr"] }


[build-dependencies]
tonic-build = "0.14.6"
tonic-prost-build = "0.14.6"
